INSERT INTO TODO (ID, USERNAME, DESCRIPTION , TARGET_DATE ,DONE)
values(10001, 'Ganesh','Learn Devops',CURRENT_DATE() , false);

INSERT INTO TODO (ID, USERNAME, DESCRIPTION , TARGET_DATE ,DONE)
values(10002, 'Raj Narayanan','Learn Java',CURRENT_DATE() , false);

INSERT INTO TODO (ID, USERNAME, DESCRIPTION , TARGET_DATE ,DONE)
values(10003, 'Raj Narayanan','Learn AWS',CURRENT_DATE() , false);

INSERT INTO TODO (ID, USERNAME, DESCRIPTION , TARGET_DATE ,DONE)
values(10004, 'Ganesh','Learn Spring',CURRENT_DATE() , false);